### ISSUE TITLE
运行打包失败

### ISSUE THREAD

**Issue by harkue** [simple-uploader/vue-uploader#136]
环境： Windows 10   
Node： v12.16.2
npm： 6.14.4

```
$ npm install
$ npm run build --report

> vue-simple-uploader@0.7.4 build D:\temp\github\vue-uploader
> node build/build.js

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'D:\temp\github\vue-uploader\build\build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-simple-uploader@0.7.4 build: `node build/build.js`
npm ERR! Exit status 1
```

**Comment by lubanproj** [comment]
怀疑是 node 版本问题，建议升级下 node 版本或者重装试试
