### ISSUE TITLE
__VERSION__ is not defined

### ISSUE THREAD

**Issue by Rebuilding127** [simple-uploader/vue-uploader#194]
新建vue项目准备使用该插件做文件上传，加入初始代码后启动报错。
vue版本：2.6.14 / 3.2.13 都试过。

```
Uncaught ReferenceError: __VERSION__ is not defined at eval (index.js?7225:10:1) at ./node_modules/vue-simple-uploader/src/index.js (chunk-vendors.js:745:1) at __webpack_require__ (app.js:307:33) at fn (app.js:563:21) at eval (main.js:3:81) at ./src/main.js (app.js:214:1) at __webpack_require__ (app.js:307:33) at app.js:1488:109 at __webpack_require__.O (app.js:353:23) at app.js:1489:53
 eval @ index.js?7225:10 
 ./node_modules/vue-simple-uploader/src/index.js @ chunk-vendors.js:745 
 __webpack_require__ @ app.js:307 
 fn @ app.js:563 
 eval @ main.js:3 
 ./src/main.js @ app.js:214 
 __webpack_require__ @ app.js:307 
 (anonymous) @ app.js:1488 
 __webpack_require__.O @ app.js:353 
 (anonymous) @ app.js:1489 
 (anonymous) @ app.js:1491 
```

**Comment by Rebuilding127** [comment]
刚刚发现存在vue3分支的bate版本，切换尝试使用，正常运行。
希望早日发布正式版本，感谢~
