### ISSUE TITLE
使用SSG方式构建时有几处`Cannot read properties of null`报错

### ISSUE THREAD

**Issue by Rebuilding127** [simple-uploader/vue-uploader#219]
使用`vitesse`做模板开发时，由于默认添加使用`vite-ssg`做为build工具，在打包时出现报错。
用的是vue3版本。
错误日志如下：
```log
TypeError: Cannot read properties of null (reading 'length')
    at d._assignHelper (D:\Code\jav-assistant-portal\node_modules\.pnpm\vue-simple-uploader@1.0.1_vue@3.2.47\node_modules\vue-simple-uploader\dist\vue-simple-uploader.umd.js:8:12079)
    at d.assignDrop (D:\Code\jav-assistant-portal\node_modules\.pnpm\vue-simple-uploader@1.0.1_vue@3.2.47\node_modules\vue-simple-uploader\dist\vue-simple-uploader.umd.js:8:12355)
    at Object.<anonymous> (D:\Code\jav-assistant-portal\node_modules\.pnpm\vue-simple-uploader@1.0.1_vue@3.2.47\node_modules\vue-simple-uploader\dist\vue-simple-uploader.umd.js:8:23214)
```

**Comment by dolymood** [comment]
1.0.2
