### ISSUE TITLE
分块上传支持同步吗？

### ISSUE THREAD

**Issue by hejiv5** [simple-uploader/vue-uploader#40]
分块上传怎么支持同步吗，目前上传后台接受的块顺序是打乱的

**Comment by dolymood** [comment]
同步？那就设置并发是1就可以了吧

**Comment by hejiv5** [comment]
不行哦，比如我的分成三块上传，后台接受的时候是先接受到第三个模块在接受到第一个和第二个模块

**Comment by dolymood** [comment]
不会，这个发送肯定是按照顺序发送的，如果同时上传是1个的话，那就是一个接一个

**Comment by hejiv5** [comment]
之前设置simultaneousUploads没起作用，以为不行，今天试了一下，原来是可以的，但是现在有个新的问题，就是点击暂停的时候，后台会报
Caused by: java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: Unexpected EOF read on the socket
	at org.apache.catalina.connector.Request.parseParts(Request.java:2919) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.Request.parseParameters(Request.java:3215) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.Request.getParameter(Request.java:1145) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:381) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:75) [spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 27 common frames omitted
Caused by: org.apache.tomcat.util.http.fileupload.FileUploadException: Unexpected EOF read on the socket
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:308) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.Request.parseParts(Request.java:2871) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	... 31 common frames omitted
Caused by: java.io.EOFException: Unexpected EOF read on the socket
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:718) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11InputBuffer.access$300(Http11InputBuffer.java:40) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11InputBuffer$SocketInputBuffer.doRead(Http11InputBuffer.java:1063) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:140) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11InputBuffer.doRead(Http11InputBuffer.java:257) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.Request.doRead(Request.java:574) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:326) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:642) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:349) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:183) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.8.0_121]
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:132) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:977) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:881) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.io.InputStream.read(InputStream.java:101) ~[na:1.8.0_121]
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:98) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:68) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.MultipartStream.readBodyData(MultipartStream.java:571) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.MultipartStream.discardBodyData(MultipartStream.java:595) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.MultipartStream.skipPreamble(MultipartStream.java:613) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:874) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:854) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:256) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:280) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	... 32 common frames omitted

**Comment by yuehui1** [comment]
> 前设置simultaneousUploads没起作用，以为不行，今天试了一下，原来是可以的，但是现在有个新的问题，就是点击暂停的时候，后台会报

请问你的问题解决了吗
